import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppStrings {
  AppStrings(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppStrings> delegate = _AppStringsDelegate();

  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings)!;

  static const List<Locale> supportedLocales = <Locale>[
    Locale('de'),
    Locale('en'),
    Locale('ar'),
  ];

  static const Map<String, Map<String, String>> _values = {
    'de': {
      'appName': 'Salaty',
      'tagline': 'Weniger Ablenkung. Mehr Salah.',
      'getStarted': "Los geht's",
      'home': 'Home',
      'tracker': 'Tracker',
      'qibla': 'Qibla',
      'settings': 'Einstellungen',
      'nextPrayer': 'Nächstes Gebet',
      'today': 'Heute',
      'prayed': 'Gebetet',
      'snoozed': 'Verschoben',
      'skipped': 'Übersprungen',
      'missed': 'Nicht bestätigt',
      'upcoming': 'Bevorstehend',
      'active': 'Aktiv',
      'pending': 'Prayer Focus',
      'refresh': 'Aktualisieren',
      'location': 'Standort',
      'useLocation': 'Standort verwenden',
      'chooseCity': 'Stadt auswählen',
      'city': 'Stadt',
      'country': 'Land',
      'continue': 'Weiter',
      'back': 'Zurück',
      'prayerTimes': 'Gebetszeiten',
      'timesQuestion': 'Stimmen diese Zeiten ungefähr mit deiner Moschee überein?',
      'yes': 'Ja',
      'adjust': 'Anpassen',
      'graceQuestion': 'Wann sollen wir dich stärker erinnern?',
      'minutesAfter': 'Minuten nach Gebetsbeginn',
      'distractions': 'Welche Apps lenken dich häufig ab?',
      'focusExplain': 'Prayer Focus hilft dir, Ablenkungen für ein paar Minuten auszuschalten. Du behältst immer die Kontrolle.',
      'enableFocus': 'Prayer Focus aktivieren',
      'permissions': 'Berechtigungen',
      'permissionExplain': 'Wir fragen Berechtigungen erst dann an, wenn sie für eine Funktion gebraucht werden.',
      'finish': 'Fertig',
      'confirmPrayer': 'Wallah, ich habe gebetet',
      'snooze': '20 Minuten später erinnern',
      'snoozeIn': 'In {minutes} Minuten erinnern',
      'skipToday': 'Heute überspringen',
      'skipConfirmTitle': 'Erinnerung beenden?',
      'skipConfirmBody': 'Möchtest du die Erinnerung für dieses Gebet wirklich beenden?',
      'noPrayLater': 'Nein, ich bete noch',
      'yesEnd': 'Ja, Erinnerung beenden',
      'emergencyUnlock': 'Notfall – Focus Mode beenden',
      'emergencyBody': 'Prayer Focus wird sofort beendet. Das Gebet wird dabei nicht als übersprungen markiert.',
      'focusTitle': 'Zeit für {prayer}',
      'focusBody': 'Du wolltest dir Zeit für dein Gebet nehmen. Lege dein Handy für ein paar Minuten weg und bete.',
      'accepted': 'Alhamdulillah 🤍',
      'week': 'Diese Woche',
      'month': 'Monat',
      'confirmedPrayers': 'Bestätigte Gebete',
      'calculationMethod': 'Berechnungsmethode',
      'madhhab': 'Asr-Berechnung',
      'standard': 'Standard',
      'hanafi': 'Hanafi',
      'highLatitude': 'Hohe Breitengrade',
      'gracePeriod': 'Grace Period',
      'snoozeDuration': 'Snooze-Dauer',
      'confirmationText': 'Bestätigungstext',
      'focusMode': 'Prayer Focus',
      'softReminder': 'Sanfte Erinnerung nach Überspringen',
      'theme': 'Darstellung',
      'system': 'System',
      'light': 'Hell',
      'dark': 'Dunkel',
      'language': 'Sprache',
      'german': 'Deutsch',
      'english': 'Englisch',
      'arabic': 'Arabisch',
      'notificationPermission': 'Benachrichtigungen erlauben',
      'exactAlarmPermission': 'Präzise Erinnerungen erlauben',
      'focusAuthorization': 'Focus-Berechtigung einrichten',
      'selectApps': 'Ablenkende Apps auswählen',
      'individualAppsOnly': 'Wähle nur einzelne ablenkende Apps aus. Ganze Kategorien werden aus Sicherheitsgründen nicht blockiert. Lass Salaty und wichtige Apps wie Telefon, Karten oder medizinische Apps ungewählt.',
      'focusFallback': 'Auf diesem Gerät ist systemweites App-Shielding nicht verfügbar. Der sichere In-App-Focus bleibt aktiv.',
      'qiblaDirection': 'Qibla-Richtung',
      'calibrate': 'Bewege dein Handy in Form einer Acht, wenn der Kompass ungenau wirkt.',
      'noCompass': 'Kein Kompass-Sensor verfügbar. Die Qibla-Richtung wird in Grad angezeigt.',
      'needLocation': 'Bitte zuerst einen Standort festlegen.',
      'offlineCache': 'Offline-Cache wird verwendet.',
      'retry': 'Erneut versuchen',
      'noData': 'Für heute sind keine zuverlässigen Gebetszeiten gespeichert.',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'manualAdjustments': 'Minutenkorrekturen',
      'maxSnoozes': 'Maximale Snoozes',
      'unlimited': 'Unbegrenzt',
      'genericError': 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
      'locationError': 'Der Standort konnte nicht bestimmt werden. Du kannst stattdessen eine Stadt auswählen.',
      'networkError': 'Die Gebetszeiten konnten gerade nicht geladen werden. Gespeicherte Daten werden verwendet, wenn sie verfügbar sind.',
      'prayerDataError': 'Die Gebetszeiten konnten nicht zuverlässig verarbeitet werden. Bitte versuche es erneut.',
      'snoozeUnavailable': 'Dieses Gebet kann nicht weiter verschoben werden.',
      'prayerFirst': 'Gebet zuerst, Handy danach.',
      'heading': 'Ausrichtung',
    },
    'en': {
      'appName': 'Salaty',
      'tagline': 'Less distraction. More Salah.',
      'getStarted': 'Get started',
      'home': 'Home',
      'tracker': 'Tracker',
      'qibla': 'Qibla',
      'settings': 'Settings',
      'nextPrayer': 'Next prayer',
      'today': 'Today',
      'prayed': 'Prayed',
      'snoozed': 'Snoozed',
      'skipped': 'Skipped',
      'missed': 'Not confirmed',
      'upcoming': 'Upcoming',
      'active': 'Active',
      'pending': 'Prayer Focus',
      'refresh': 'Refresh',
      'location': 'Location',
      'useLocation': 'Use my location',
      'chooseCity': 'Choose city',
      'city': 'City',
      'country': 'Country',
      'continue': 'Continue',
      'back': 'Back',
      'prayerTimes': 'Prayer times',
      'timesQuestion': 'Do these times roughly match your local mosque?',
      'yes': 'Yes',
      'adjust': 'Adjust',
      'graceQuestion': 'When should we remind you more strongly?',
      'minutesAfter': 'minutes after prayer begins',
      'distractions': 'Which apps often distract you?',
      'focusExplain': 'Prayer Focus helps you reduce distractions for a few minutes. You always remain in control.',
      'enableFocus': 'Enable Prayer Focus',
      'permissions': 'Permissions',
      'permissionExplain': 'We only request permissions when a feature actually needs them.',
      'finish': 'Finish',
      'confirmPrayer': 'I have prayed',
      'snooze': 'Remind me in 20 minutes',
      'snoozeIn': 'Remind me in {minutes} minutes',
      'skipToday': 'Skip today',
      'skipConfirmTitle': 'End reminder?',
      'skipConfirmBody': 'Do you really want to end reminders for this prayer?',
      'noPrayLater': 'No, I will pray',
      'yesEnd': 'Yes, end reminder',
      'emergencyUnlock': 'Emergency – end Focus Mode',
      'emergencyBody': 'Prayer Focus ends immediately. The prayer will not be marked as skipped.',
      'focusTitle': 'Time for {prayer}',
      'focusBody': 'You wanted to make time for prayer. Put your phone down for a few minutes and pray.',
      'accepted': 'Alhamdulillah 🤍',
      'week': 'This week',
      'month': 'Month',
      'confirmedPrayers': 'Confirmed prayers',
      'calculationMethod': 'Calculation method',
      'madhhab': 'Asr calculation',
      'standard': 'Standard',
      'hanafi': 'Hanafi',
      'highLatitude': 'High latitude rule',
      'gracePeriod': 'Grace period',
      'snoozeDuration': 'Snooze duration',
      'confirmationText': 'Confirmation text',
      'focusMode': 'Prayer Focus',
      'softReminder': 'Gentle reminder after skip',
      'theme': 'Appearance',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'language': 'Language',
      'german': 'German',
      'english': 'English',
      'arabic': 'Arabic',
      'notificationPermission': 'Allow notifications',
      'exactAlarmPermission': 'Allow precise reminders',
      'focusAuthorization': 'Set up Focus permission',
      'selectApps': 'Select distracting apps',
      'individualAppsOnly': 'Select only individual distracting apps. Whole categories are not blocked for safety. Leave Salaty and essential apps such as Phone, Maps or medical apps unselected.',
      'focusFallback': 'System-wide app shielding is not available on this device. Safe in-app Focus remains active.',
      'qiblaDirection': 'Qibla direction',
      'calibrate': 'Move your phone in a figure eight if the compass seems inaccurate.',
      'noCompass': 'No compass sensor is available. Qibla is still shown in degrees.',
      'needLocation': 'Please set a location first.',
      'offlineCache': 'Using offline cache.',
      'retry': 'Try again',
      'noData': 'No reliable prayer times are stored for today.',
      'save': 'Save',
      'cancel': 'Cancel',
      'manualAdjustments': 'Minute adjustments',
      'maxSnoozes': 'Maximum snoozes',
      'unlimited': 'Unlimited',
      'genericError': 'Something went wrong. Please try again.',
      'locationError': 'Your location could not be determined. You can choose a city instead.',
      'networkError': 'Prayer times could not be loaded right now. Cached data will be used when available.',
      'prayerDataError': 'Prayer times could not be processed reliably. Please try again.',
      'snoozeUnavailable': 'This prayer cannot be snoozed any further.',
      'prayerFirst': 'Prayer first, phone second.',
      'heading': 'Heading',
    },
    'ar': {
      'appName': 'صلاتي',
      'tagline': 'تشتيت أقل. صلاة أكثر.',
      'getStarted': 'ابدأ',
      'home': 'الرئيسية',
      'tracker': 'المتابعة',
      'qibla': 'القبلة',
      'settings': 'الإعدادات',
      'nextPrayer': 'الصلاة القادمة',
      'today': 'اليوم',
      'prayed': 'تمت الصلاة',
      'snoozed': 'مؤجل',
      'skipped': 'تم الإنهاء',
      'missed': 'غير مؤكد',
      'upcoming': 'قادمة',
      'active': 'حان وقتها',
      'pending': 'تركيز الصلاة',
      'refresh': 'تحديث',
      'location': 'الموقع',
      'useLocation': 'استخدم موقعي',
      'chooseCity': 'اختر مدينة',
      'city': 'المدينة',
      'country': 'الدولة',
      'continue': 'متابعة',
      'back': 'رجوع',
      'prayerTimes': 'مواقيت الصلاة',
      'timesQuestion': 'هل تتوافق هذه الأوقات تقريبًا مع مسجدك؟',
      'yes': 'نعم',
      'adjust': 'تعديل',
      'graceQuestion': 'متى تريد تذكيرًا أقوى؟',
      'minutesAfter': 'دقيقة بعد دخول وقت الصلاة',
      'distractions': 'ما التطبيقات التي تشتتك غالبًا؟',
      'focusExplain': 'يساعدك وضع تركيز الصلاة على تقليل المشتتات لبضع دقائق، وتبقى أنت المتحكم دائمًا.',
      'enableFocus': 'تفعيل تركيز الصلاة',
      'permissions': 'الأذونات',
      'permissionExplain': 'نطلب الأذونات فقط عندما تحتاجها ميزة معينة.',
      'finish': 'إنهاء',
      'confirmPrayer': 'لقد صليت',
      'snooze': 'ذكرني بعد 20 دقيقة',
      'snoozeIn': 'ذكّرني بعد {minutes} دقيقة',
      'skipToday': 'إنهاء تذكير اليوم',
      'skipConfirmTitle': 'إنهاء التذكير؟',
      'skipConfirmBody': 'هل تريد فعلًا إنهاء التذكيرات لهذه الصلاة؟',
      'noPrayLater': 'لا، سأصلي',
      'yesEnd': 'نعم، أنهِ التذكير',
      'emergencyUnlock': 'طوارئ – إنهاء وضع التركيز',
      'emergencyBody': 'سيتم إنهاء وضع التركيز فورًا، ولن يتم تسجيل الصلاة على أنها متخطاة.',
      'focusTitle': 'حان وقت {prayer}',
      'focusBody': 'أردت أن تخصص وقتًا للصلاة. اترك الهاتف لبضع دقائق وصلِّ.',
      'accepted': 'الحمد لله 🤍',
      'week': 'هذا الأسبوع',
      'month': 'الشهر',
      'confirmedPrayers': 'الصلوات المؤكدة',
      'calculationMethod': 'طريقة الحساب',
      'madhhab': 'حساب العصر',
      'standard': 'قياسي',
      'hanafi': 'حنفي',
      'highLatitude': 'قاعدة خطوط العرض العليا',
      'gracePeriod': 'فترة السماح',
      'snoozeDuration': 'مدة التأجيل',
      'confirmationText': 'نص التأكيد',
      'focusMode': 'تركيز الصلاة',
      'softReminder': 'تذكير لطيف بعد الإنهاء',
      'theme': 'المظهر',
      'system': 'النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'language': 'اللغة',
      'german': 'الألمانية',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'notificationPermission': 'السماح بالإشعارات',
      'exactAlarmPermission': 'السماح بالتذكيرات الدقيقة',
      'focusAuthorization': 'إعداد إذن التركيز',
      'selectApps': 'اختر التطبيقات المشتتة',
      'individualAppsOnly': 'اختر تطبيقات مشتتة منفردة فقط. لا يتم حجب فئات كاملة لأسباب تتعلق بالسلامة. اترك تطبيق صلاتي والتطبيقات الأساسية مثل الهاتف والخرائط والتطبيقات الطبية دون تحديد.',
      'focusFallback': 'حجب التطبيقات على مستوى النظام غير متاح على هذا الجهاز. يبقى وضع التركيز داخل التطبيق فعالًا.',
      'qiblaDirection': 'اتجاه القبلة',
      'calibrate': 'حرّك هاتفك على شكل رقم ثمانية إذا بدا البوصلة غير دقيقة.',
      'noCompass': 'لا يوجد مستشعر بوصلة. سيظهر اتجاه القبلة بالدرجات.',
      'needLocation': 'حدد موقعًا أولًا.',
      'offlineCache': 'يتم استخدام البيانات المحفوظة دون اتصال.',
      'retry': 'حاول مجددًا',
      'noData': 'لا توجد مواقيت صلاة موثوقة محفوظة لليوم.',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'manualAdjustments': 'تعديلات الدقائق',
      'maxSnoozes': 'أقصى عدد للتأجيل',
      'unlimited': 'بلا حد',
      'genericError': 'حدث خطأ ما. حاول مرة أخرى.',
      'locationError': 'تعذر تحديد موقعك. يمكنك اختيار مدينة بدلًا من ذلك.',
      'networkError': 'تعذر تحميل مواقيت الصلاة الآن. سيتم استخدام البيانات المحفوظة إن كانت متاحة.',
      'prayerDataError': 'تعذر معالجة مواقيت الصلاة بشكل موثوق. حاول مرة أخرى.',
      'snoozeUnavailable': 'لا يمكن تأجيل تذكير هذه الصلاة أكثر.',
      'prayerFirst': 'الصلاة أولًا، ثم الهاتف.',
      'heading': 'اتجاه الهاتف',
    },
  };

  String t(String key, {Map<String, String> params = const <String, String>{}}) {
    String value = _values[locale.languageCode]?[key] ??
        _values['en']?[key] ??
        key;
    for (final MapEntry<String, String> entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppStrings.supportedLocales.any((Locale item) => item.languageCode == locale.languageCode);

  @override
  Future<AppStrings> load(Locale locale) => SynchronousFuture<AppStrings>(AppStrings(locale));

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppStrings> old) => false;
}
